  - name: Destroy a server instance
    os_server:
      cloud: ospcloud
      name: "{{ instance_name }}"
      image: rhel-guest
      flavor: m2.small
      state: absent
      delete_fip: yes
      wait: yes
