---
# Use Jumpbox to provision OpenStack
- hosts: jumpbox
  roles:
     - osp.network
     - osp.keypair
     - osp.securitygroup
     - osp.flavor
  tasks:
  - name: Create frontend instance
    include_role:
       name: osp.instance
       vars_from: frontend.yaml
  - name: Create app1 instance
    include_role:
       name: osp.instance
       vars_from: app1.yaml
  - name: Create app2 instance
    include_role:
       name: osp.instance
       vars_from: app2.yaml
  - name: Create db instance
    include_role:
       name: osp.instance
       vars_from: db.yaml
  - name: Gather facts
    include_role: 
       name: osp.facts

# Better ansible.

- name: prepare
  hosts: all
  become: true
  roles:
  - name: prepare

- name: deploy frontends
  hosts: frontends
  become: true
  roles:
  - name: frontends

- name: deploy appdbs
  hosts: appdbs
  become: true
  roles:
  - name: geerlingguy.postgresql

- name: deploy appservers
  hosts: apps
  become: true
  roles:
  - name: appservers
