---
# tasks file for ./frontends
- name: install packages
  package:
    name: '{{ item }}'
    state: latest
  loop:
    - httpie
    - haproxy
- name: enable HAProxy
  service:
    name: haproxy
    enabled: yes
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restart haproxy