---
# Better ansible.

- name: wait 30 minutes for new Prod environment
  hosts: localhost
  pause:
    minutes: 30

- name: reload inventory
  hosts: prod
  ping:
  meta: refresh_inventory
    
- name: prepare
  hosts: prod
  become: true
  roles:
  - name: prepare


- name: deploy frontends
  hosts: frontends
  roles:
  - name: frontends

- name: deploy appdbs
  hosts: appdbs
  become: true
  roles:
  - name: geerlingguy.postgresql

- name: deploy appservers
  hosts: apps
  become: true
  roles:
  - name: appservers